# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LandChangeDetector
                                 A QGIS plugin
 Bi-temporal land use change detection
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-04-06
        copyright            : (C) 2026 by Mohammed Radhoine Amara
        email                : mohammed.radhoine.amara@ensia.edu.dz
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LandChangeDetector class from file LandChangeDetector.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .land_change_detector import LandChangeDetector
    return LandChangeDetector(iface)
